steps:

  - name: 'gcr.io/angular-34bc8/firebase'     # autenticazione firebase 
    args: ['use', 'angular-34bc8', '--token', '${_FIREBASE_TOKEN}']
  - name: 'gcr.io/angular-34bc8/firebase'     # a quale progetto vuole accedere
    args: ['target:apply', 'hosting', 'angular-34bc8', 'angular-34bc8', '--token', '${_FIREBASE_TOKEN}']
  - name: 'gcr.io/angular-34bc8/firebase'     # deploy finale del progetto
    args: ['deploy', '--token', '${_FIREBASE_TOKEN}', '--only', 'hosting:angular-34bc8']
timeout: 1200s